version: "3.9"

services:
  # Frontend service (Nginx để serve static files)
  frontend:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - nafood-network

  # Backend service
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb+srv://admin:UTEIjifcllB420pH@lamv.tzc1slv.mongodb.net/nafood
      - JWT_SECRET=nafood_jwt_secret_key_2024
      - PORT=5000
      - CORS_ORIGIN=http://localhost:3000
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - nafood-network
    restart: unless-stopped

  # MongoDB service - DISABLED (Using MongoDB Atlas)
  # mongo:
  #   image: mongo:7.0
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     - MONGO_INITDB_DATABASE=nafood
  #   volumes:
  #     - mongo-data:/data/db
  #     - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  #   networks:
  #     - nafood-network
  #   restart: unless-stopped

  # MongoDB Express - DISABLED (Using MongoDB Atlas)
  # mongo-express:
  #   image: mongo-express:latest
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     - ME_CONFIG_MONGODB_SERVER=mongo
  #     - ME_CONFIG_MONGODB_PORT=27017
  #     - ME_CONFIG_BASICAUTH_USERNAME=admin
  #     - ME_CONFIG_BASICAUTH_PASSWORD=admin123
  #   depends_on:
  #     - mongo
  #   networks:
  #     - nafood-network
  #   restart: unless-stopped

# volumes:
  # mongo-data:
  #   driver: local

networks:
  nafood-network:
    driver: bridge
